name: Add need-rebase label if the branch is >= 50 commits behind

on:
  pull_request_target:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  behind:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3                                               
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: |
          echo ::set-output name=behind_by::$(git log --oneline origin/${{ github.event.pull_request.base.ref }} ^${{ github.head_ref }} | wc -l)
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: need-rebase
