name: docker

on:
  push:
    branches:
      - master
      - 'stable/**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Some vars
        id: vars
        run: |
          echo ::set-output name=commit_hash::${GITHUB_SHA::10}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/alpine/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frr:master
          build-args: PKGVER=${{ steps.vars.outputs.commit_hash }}
