name: Build daily 'master' images for Docker

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_daily_master:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Custom variables
        id: vars
        run: |
          # To package a specific git commit, the date of the commit gets
          # appended to the latest release, e.g. 1.0.0_git20180204.
          # This is the requirement by APKBUILD (abuild).
          # More details: https://wiki.alpinelinux.org/wiki/APKBUILD_Reference.
          echo ::set-output name=date::$(date +'%Y%m%d')

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ton31337+github
          password: MP2680XX30GTTII1N7MZKC3RXQLMGY4E713351O3EZAH7V90OM658325JWZCTA86

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/alpine/Dockerfile
          push: true
          tags: quay.io/ton31337/tests:master
          build-args: PKGVER=${{ steps.vars.outputs.date }}
          platforms: linux/amd64
