name: Build daily 'master' image for Docker

#on:
#  schedule:
#    - cron: "59 23 * * *"
#    - timezone: UTC
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Some vars
        id: vars
        run: |
          echo ::set-output name=commit_hash::${GITHUB_SHA::8}
          echo ::set-output name=date::$(date +'%Y%m%d')

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/alpine/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frr:master
          build-args: PKGVER=${{ steps.vars.outputs.date }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x
