name: Labeler

on:
  issue_comment:
    types: [created, edited, deleted]
  pull_request_review_comment:
    types: [created ,edited, deleted]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: github/issue-labeler@v2.5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
