name: Labeler

on:
  pull_request_target:
    types: [opened, reopened]
  pull_request_comment:
    types: [edited, submitted, dismissed]
  pull_request_review_comment:
    types: [edited, submitted, dismissed]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: github/issue-labeler@v2.5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
